# Generated by Django 5.2.4 on 2025-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='students/')),
                ('type', models.CharField(choices=[('BSCS', 'COMPUTER SCIENCE'), ('BSIT', 'INFORMATION TECHNOLOGY'), ('BSSE', 'SOFTWARE ENGEERENING'), ('BSDS', 'DATA SCIENCE')], max_length=4)),
            ],
        ),
    ]
